image: privacybydesign/node_yarn:latest

stages:
  - build

before_script:
  - set -euxo pipefail
  - yarn install

build:
  stage: build
  script:
    - yarn run build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - dist/*
